---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update machine
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          declare -a packages=()
          declare -a essential_packages=()
          apt-cache depends --recurse --important --installed apt
          apt-cache depends --recurse --important --installed --quiet apt
          apt-cache depends --recurse --important --installed --quiet=2 apt
          while read -r package essential; do
            if [[ "$essential" == 'yes' ]]; then
              essential_packages+=("$package")
            fi
          done < <(dpkg-query -Wf '${Package} ${Essential}\n')
          sudo apt-get --assume-yes purge "${packages[@]}"
          sudo apt-get --assume-yes update
          sudo apt-get --assume-yes dist-upgrade
      - name: Install mkosi
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get --assume-yes install mkosi yum
      - name: Build image
        run: sudo mkosi -C $GITHUB_WORKSPACE/ --force build
