---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Install rpm dependencies (apt)
        run: sudo apt-get -y install autopoint libnss3-dev libpopt-dev
      - name: Download rpm
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/rpm
          ref: rpm-4.15.x
          path: rpm
      - name: Install rpm
        working-directory: ${{ github.workspace }}/rpm
        run: |
          ./autogen.sh --enable-python --with-cap --with-acl
          make
          sudo make install
      - name: Download dnf
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/dnf
          ref: 4.2.18
          path: dnf
      - name: Install dnf
        working-directory: ${{ github.workspace }}/dnf
        run: |
          mkdir build
          pushd build
          cmake -DPYTHON_DESIRED=3 -DWITH_MAN=0 ..
          make
          sudo make install
          sudo ln -s /usr/local/bin/dnf-3 /usr/local/bin/dnf
          sudo ln -s /usr/local/bin/dnf-automatic-3 /usr/local/bin/dnf-automatic
          popd
      - name: Download mkosi
        uses: actions/checkout@v2
        with:
          repository: systemd/mkosi
          path: mkosi
      - name: Install python-setuptools
        run: sudo pip3 install setuptools
      - name: Install mkosi
        working-directory: ${{ github.workspace }}/mkosi
        run: sudo python3 setup.py install
      - name: Cache packages
        id: package-cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/image-definition/mkosi.cache
          key: mkosi-cache
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: image-definition
      - name: Build image
        run: sudo mkosi -C "$GITHUB_WORKSPACE/image-definition" --force build
