---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install mkosi
        env:
          DEBIAN_FRONTEND=noninteractive
        run: sudo apt-get install -y --force-yes mkosi
      - name: Build image
        run: sudo mkosi -C $GITHUB_WORKSPACE/ --force build
