---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Download dnf
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/dnf
          ref: 4.2.18
          path: dnf
      - name: Install dnf
        working-directory: ${{ github.workspace }}/dnf
        run: |
          mkdir build
          pushd build
          cmake -DPYTHON_DESIRED=3 -DWITH_MAN=0 ..
          make
          sudo make install
          popd
      - name: Download mkosi
        uses: actions/checkout@v2
        with:
          repository: systemd/mkosi
          ref: v5
          path: mkosi
      - name: Install mkosi
        working-directory: ${{ github.workspace }}/mkosi
        run: sudo python3 setup.py install
      - name: Cache packages
        id: package-cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/image-definition/mkosi.cache
          key: mkosi-cache
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: image-definition
      - name: Build image
        run: sudo mkosi -C "$GITHUB_WORKSPACE/image-definition" --force build
