---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    container: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Image
        run: |
          sudo dnf --assumeyes install mkosi pacman zypper apt
          tree $GITHUB_WORKSPACE/
          sudo mkosi -C $GITHUB_WORKSPACE/ --force build
          tree $GITHUB_WORKSPACE/
