---
name: Build Image
on: [push]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update System
        run: |
          sudo apt update
          auso apt upgrade
      - name: Install Dependencies
        run: sudo apt install git python3
      - name: Install mkosi
        run: git clone https://github.com/systemd/mkosi.git
      - name: Build Image
        run: sudo python3 ./mkosi/mkosi -C $GITHUB_WORKSPACE/ --force
